import Head from "next/head";
import { Banner } from "./components/Banner";
import { Team } from "./components/Team";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Sócia App</title>
      </Head>
      <Banner />
      <Team />
    </>
  );
}
